title:            Notes of a Statistics Watcher
description:      Kris Sankaran's Blog
logo:             site-logo.png
#Comment out url when working locally to resolve base urls correctly
url:	     	 http://krisrs1128.github.io/info-uncertainty/

# Owner/author information
owner:
  name:           Kris Sankaran
  avatar:         kris-sankaran-photo.jpg
  email:          krissankaran@stanford.edu

# Internal pages/posts to include in top navigation
links:
  - title: About
    url: /about
  - title: Articles
    url: /articles

highlighter: rouge

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "so-simple-theme.sublime-project", "so-simple-theme.sublime-workspace"]
